name: Request Recyled
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9414032446220517
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#706557'
    - '#fefefe'
    - '#f6931d'
    - '#00ff00'
    - '#000000'
  brandStrength: 0
  lightness: 0.875
  saturation: 0.9016634789295495
  rhythmicContrast: 0.17555329063907266
purpose: []
